lang_char: 'None'
experiment_name: 'bg_lps'
train_data: '/content/dataset'
valid_data: '/content/val'
manualSeed: 1111
workers: 2
batch_size: 1 #32
num_iter: 100000
valInterval: 2000
saved_model: '' #'saved_models/en_filtered/iter_300000.pth'
FT: True
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: '/content/dataset' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 80
imgW: 240
rgb: True
contrast_adjust: False
sensitive: False
PAD: True
contrast_adjust: 0.0
data_filtering_off: True
# Model Architecture
Transformation: 'TPS'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 3
output_channel: 512
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
